INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Tereza', '(67) 99999-8888', 'tereza@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Roberto', '(67) 99999-8888', 'roberto@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Ryan', '(67) 99999-8888', 'ryan@gmail.com', '1234', now());
INSERT INTO tb_tecnico (nome, telefone, email, senha, created_at) VALUES ('Angelica', '(67) 99999-8888', 'angelica@gmail.com', '1234', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '789456', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Desktop Dell', '789458', 'Manutenção', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Projetor Epsom', '789459', 'Sala reunião', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Impressora HP', '789452', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Imprssora 3D', '789453', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '7894564', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '789456', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Desktop Dell', '789458', 'Manutenção', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Projetor Epsom', '789459', 'Sala reunião', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Impressora HP', '789452', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Imprssora 3D', '789453', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '7894564', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '789456', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Desktop Dell', '789458', 'Manutenção', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Projetor Epsom', '789459', 'Sala reunião', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Impressora HP', '789452', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Imprssora 3D', '789453', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '7894564', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '789456', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Desktop Dell', '789458', 'Manutenção', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Projetor Epsom', '789459', 'Sala reunião', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Impressora HP', '789452', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Imprssora 3D', '789453', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '7894564', 'Sala Projetos', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('NoteBook', '789456', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Desktop Dell', '789458', 'Manutenção', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Projetor Epsom', '789459', 'Sala reunião', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Impressora HP', '789452', 'Administrativo', now());
INSERT INTO tb_equipamento (equipamento, patrimonio, setor, created_at) VALUES ('Imprssora 3D', '789453', 'Sala Projetos', now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Impressora não conecta', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Impressora não conecta', 'pendente', 'Baixa', 'PENDENTE', 4, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-02-15', 'Desktop não liga', 'pendente','Baixa', 'CANCELADO', 4, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-03-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 3, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-02-01', 'Desktop não liga', 'pendente', 'Baixa', 'CANCELADO', 3, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2021-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2021-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'NoteBook sem acesso a internet', 'pendente', 'Baixa', 'PENDENTE', 4, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 3, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2021-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2021-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2021-01-01', 'Projetor não liga', 'Projetor arrumado', 'Alta', 'EFETIVADO', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Roteador reiniciando sozinho', 'Roteador trocado', 'Baixa', 'EFETIVADO', 1, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 4, now());
INSERT INTO tb_ordem_servico(data_cadastro, descricao_problema, descricao_solucao, prioridade, status, id_tecnico_fk, created_at) VALUES ('2022-01-01', 'Desktop não liga', 'pendente', 'Baixa', 'PENDENTE', 2, now());
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (1, 6);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (6, 2);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (10, 1);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (15, 10);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (14, 8);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (8, 9);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (9, 5);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (11, 15);
INSERT INTO tb_ordem_has_equipamento(id_ordem, id_equipamento) VALUES (18, 3);